import { router, protectedProcedure, publicProcedure } from "@arcade-vibe/api";
import { db } from "@arcade-vibe/db";
import { prompts } from "@arcade-vibe/db/schema/prompts";
import { games } from "@arcade-vibe/db/schema/games";
import { generateGame } from "@arcade-vibe/api/lib/game-generation";
import { z } from "zod";
import { eq, desc, and, isNotNull, notInArray } from "drizzle-orm";
import { TRPCError } from "@trpc/server";

export const promptRunsRouter = router({
  /**
   * Run another user's public prompt with a different model
   * Supports BYOK via apiKeyId
   * Streams the generation process
   */
  create: protectedProcedure
    .input(
      z.object({
        promptId: z.string().uuid(),
        modelKey: z.string().min(1),
        apiKeyId: z.string().uuid().optional(),
      }),
    )
    .mutation(async function* ({ input, ctx }) {
      if (!ctx.user) {
        throw new TRPCError({
          code: "UNAUTHORIZED",
          message: "User not authenticated",
        });
      }

      // Fetch prompt with author for the response
      const prompt = await db.query.prompts.findFirst({
        where: eq(prompts.id, input.promptId),
        with: {
          user: {
            columns: {
              id: true,
              name: true,
              email: true,
              image: true,
            },
          },
        },
      });

      if (!prompt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Prompt not found",
        });
      }

      // Use shared generation logic with public prompt requirement
      const result = await generateGame({
        promptId: input.promptId,
        modelKey: input.modelKey,
        userId: ctx.user.id,
        apiKeyId: input.apiKeyId,
        creditReason: "Community prompt run",
        requirePublicPrompt: true,
      });

      // Stream events from the generator
      for await (const event of result.stream) {
        switch (event.type) {
          case "chunk":
            yield {
              type: "chunk",
              gameId: event.gameId,
              promptId: input.promptId,
              promptAuthor: prompt.user,
              code: event.code,
              highlighted: event.highlighted,
              isComplete: false,
            };
            break;
          case "complete":
            yield {
              type: "complete",
              gameId: event.gameId,
              promptId: input.promptId,
              promptAuthor: prompt.user,
              assetUrl: event.assetUrl,
              isComplete: true,
            };
            break;
          case "error":
            yield {
              type: "error",
              gameId: event.gameId,
              promptId: input.promptId,
              promptAuthor: prompt.user,
              error: event.error,
              isComplete: true,
            };
            break;
        }
      }
    }),

  /**
   * List all runs of a public prompt
   * Includes games generated by users running others' prompts
   * Supports pagination
   */
  listByPrompt: publicProcedure
    .input(
      z.object({
        promptId: z.string().uuid(),
        limit: z.number().int().min(1).max(100).default(50),
        offset: z.number().int().min(0).default(0),
      }),
    )
    .query(async ({ input }) => {
      const prompt = await db.query.prompts.findFirst({
        where: eq(prompts.id, input.promptId),
      });

      if (!prompt) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Prompt not found",
        });
      }

      // Verify prompt is public
      if (prompt.visibility !== "public") {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Cannot list runs for non-public prompts",
        });
      }

      const gamesQuery = db.query.games;
      if (!gamesQuery) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Database query not available",
        });
      }

      const result = await gamesQuery.findMany({
        where: and(
          eq(games.promptId, input.promptId),
          eq(games.isHidden, false),
        ),
        orderBy: [desc(games.createdAt)],
        limit: input.limit,
        offset: input.offset,
        with: {
          prompt: {
            with: {
              user: {
                columns: {
                  id: true,
                  name: true,
                  email: true,
                  image: true,
                },
              },
            },
          },
          theme: true,
        },
      });

      return result;
    }),

  /**
   * List current user's runs of other users' prompts
   * Only includes games where promptId is not null
   * Supports pagination
   * Optimized to filter at database level
   */
  listMine: protectedProcedure
    .input(
      z.object({
        limit: z.number().int().min(1).max(100).default(50),
        offset: z.number().int().min(0).default(0),
      }),
    )
    .query(async ({ input, ctx }) => {
      if (!ctx.user) {
        throw new TRPCError({
          code: "UNAUTHORIZED",
          message: "User not authenticated",
        });
      }

      const userId = ctx.user.id;

      // Get all prompt IDs by this user
      const userPrompts = await db.query.prompts.findMany({
        where: eq(prompts.authorId, userId),
        columns: { id: true },
      });
      const userPromptIds = userPrompts.map((p) => p.id);

      // Query games where promptId is NOT in user's prompts
      // This filters at the database level for better performance
      const result = await db.query.games.findMany({
        where: and(
          isNotNull(games.promptId),
          eq(games.isHidden, false),
          // If user has prompts, exclude games using those prompts
          userPromptIds.length > 0
            ? notInArray(games.promptId, userPromptIds)
            : undefined,
        ),
        orderBy: [desc(games.createdAt)],
        limit: input.limit,
        offset: input.offset,
        with: {
          prompt: {
            with: {
              user: {
                columns: {
                  id: true,
                  name: true,
                  email: true,
                  image: true,
                },
              },
            },
          },
          theme: true,
        },
      });

      return result;
    }),
});
